version: '3'

services:
  web:
    image: nginx:1.15
    ports:
      - "8888:80"
    volumes:
      - ./monsite:/var/www/monsite
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    links: 
      - php  
  php:
    build:
      context: ./php-Dockerfile
    depends_on:
      - maria
    links:
      - maria
    volumes:
      - ./monsite:/var/www/monsite
  maria:
    image: mariadb
    ports:
      - "3306:3306"
    volumes:
      - ./create.sql:/docker-entrypoint-initdb.d/create.sql
    environment:
      - MYSQL_ROOT_PASSWORD=azerty

